### ISSUE TITLE
PHP 5.4 minimal

### ISSUE THREAD

**Issue by Mehdi-Bl** [bobsta63/senitor#1]
Hi Bobby,

I see: Requirements

PHP >= 5.4.0

Ubuntu 12 & Centos 6.x that we still support in sentora 1.0 are only 5.3 currently and might remain ? This update will mean API would work only on centos 7 & ubuntu 14 ?

**Comment by allebb** [comment]
Yep a minimum version of PHP 5.4 is required so if people intend on running
it on the same server as what they are connecting too then yes they must
run PHP 5.4. If people still need to use PHP 5.3 then they should use my
original client as I have no intention of providing backward compatibility
in this version.
